version: '3.6'
services:
  namenode:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-namenode:ssdp-0.0.1
    restart: always
    volumes:
      - /root/ssdp-volumes/name:/hadoop/dfs/name
    environment:
      NAMENODE_HOST: namenode
    ports:
      - 51070:50070
      - 19887:19888
      - 9000:9000

  resourcemanager:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-resourcemanager:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    ports:
      - 8087:8088

  nodemanager:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-nodemanager:ssdp-0.0.1
    restart: always
    environment:
      NAMENODE_HOST: namenode
    depends_on:
      - namenode

  historyserver:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-historyserver:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    ports:
      - 19888:19888
    
  datanode1:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-datanode:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    volumes:
      - /root/ssdp-volumes/data1:/hadoop/dfs/data

  datanode2:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-datanode:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    volumes:
      - /root/ssdp-volumes/data2:/hadoop/dfs/data

  datanode3:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hadoop-datanode:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    volumes:
      - /root/ssdp-volumes/data3:/hadoop/dfs/data

  hregion1:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hbase-region:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - zoo1
      - zoo2
      - zoo3
    environment:
      NAMENODE_HOST: namenode
      HMASTER_HOST: hmaster
      ZOOKEEPER1_HOST: zoo1
      ZOOKEEPER2_HOST: zoo2
      ZOOKEEPER3_HOST: zoo3
    ports:
      - 51011:16030
    volumes:
      - /root/ssdp-volumes/hbase/hregion1:/opt/hbase-1.3.1/zookeeper

  hregion2:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hbase-region:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - zoo1
      - zoo2
      - zoo3
    environment:
      NAMENODE_HOST: namenode
      HMASTER_HOST: hmaster
      ZOOKEEPER1_HOST: zoo1
      ZOOKEEPER2_HOST: zoo2
      ZOOKEEPER3_HOST: zoo3
    ports:
      - 51012:16030
    volumes:
      - /root/ssdp-volumes/hbase/hregion2:/opt/hbase-1.3.1/zookeeper

  hregion3:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hbase-region:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - zoo1
      - zoo2
      - zoo3
    environment:
      NAMENODE_HOST: namenode
      HMASTER_HOST: hmaster
      ZOOKEEPER1_HOST: zoo1
      ZOOKEEPER2_HOST: zoo2
      ZOOKEEPER3_HOST: zoo3
    ports:
      - 51013:16030
    volumes:
      - /root/ssdp-volumes/hbase/hregion3:/opt/hbase-1.3.1/zookeeper

  hmaster:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hbase-master:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - zoo1
      - zoo2
      - zoo3
    environment:
      NAMENODE_HOST: namenode
      ZOOKEEPER1_HOST: zoo1
      ZOOKEEPER2_HOST: zoo2
      ZOOKEEPER3_HOST: zoo3
    ports:
      - 51010:16010
    volumes:
      - /root/ssdp-volumes/hbase/hmaster:/opt/hbase-1.3.1/zookeeper

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: hive
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "ps", "-aux", "| grep [m]ysqld"]
    volumes:
      - /root/ssdp-volumes/mysql:/var/lib/mysql

  hive-server:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hive:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
      MARIADB_HOST: mariadb
    ports:
      - 16011:16010
      - 10001:10002
    volumes:
      - /root/ssdp-volumes/hive-serverlog:/tmp

  hive-metastore:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hive:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
      MARIADB_HOST: mariadb
    command: /opt/apache-hive-3.1.0-bin/bin/hive --service metastore
    ports:
      - 9083:9083
    volumes:
      - /root/ssdp-volumes/hive-serverlog:/tmp

  hue:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/hue:4.3.0
    restart: always
    ports:
      - 8887:8888
#    volumes:
#      - /root/ssdp-volumes/hue/desktop:/opt/hue/desktop

# HA cluster after here

  zoo1:
    image: zookeeper:3.4
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    healthcheck:
      test: ["CMD", "netstat", "-nlp", "| grep 2181"]
    volumes:
      - /root/ssdp-volumes/zoo1/data:/data
      - /root/ssdp-volumes/zoo1/datalog:/datalog
      - /root/ssdp-volumes/zoo1/logs:/logs

  zoo2:
    image: zookeeper:3.4
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    healthcheck:
      test: ["CMD", "netstat", "-nlp", "| grep 2181"]
    volumes:
      - /root/ssdp-volumes/zoo2/data:/data
      - /root/ssdp-volumes/zoo2/datalog:/datalog
      - /root/ssdp-volumes/zoo2/logs:/logs

  zoo3:
    image: zookeeper:3.4
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    healthcheck:
      test: ["CMD", "netstat", "-nlp", "| grep 2181"]
    volumes:
      - /root/ssdp-volumes/zoo3/data:/data
      - /root/ssdp-volumes/zoo3/datalog:/datalog
      - /root/ssdp-volumes/zoo3/logs:/logs

  spark-master:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/spark-master:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
    environment:
      NAMENODE_HOST: namenode
    volumes:
      - /root/ssdp-volumes/spark/master:/opt/spark/logs
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8998:8998"
  spark-worker-1:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/spark-worker:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - spark-master
    environment:
      NAMENODE_HOST: namenode
      SPARKMASTER_HOST: spark-master
    volumes:
      - /root/ssdp-volumes/spark/worker1:/opt/spark/logs
    ports:
      - "8081:8081"
  spark-worker-2:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/spark-worker:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - spark-master
    environment:
      NAMENODE_HOST: namenode
      SPARKMASTER_HOST: spark-master
    volumes:
      - /root/ssdp-volumes/spark/worker2:/opt/spark/logs
    ports:
      - "8082:8081"
  spark-worker-3:
    image: registry.cn-hangzhou.aliyuncs.com/ispatial/spark-worker:ssdp-0.0.1
    restart: always
    depends_on:
      - namenode
      - spark-master
    environment:
      NAMENODE_HOST: namenode
      SPARKMASTER_HOST: spark-master
    volumes:
      - /root/ssdp-volumes/spark/worker3:/opt/spark/logs
    ports:
      - "8083:8081"



